# Generated by Django 4.0 on 2021-12-31 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProyectItem',
        ),
    ]
