# Generated by Django 4.0 on 2021-12-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0002_delete_proyectitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProyecto', models.CharField(max_length=500)),
                ('boletaPoliza', models.CharField(max_length=100)),
                ('boletaFielCumplimiento', models.CharField(max_length=100)),
                ('valorUfReferencia', models.FloatField()),
                ('fehaUfReferencia', models.DateField()),
                ('presupuestoDiponible', models.CharField(max_length=200)),
                ('ofertaEconomica', models.CharField(max_length=200)),
                ('distribucion', models.FloatField()),
                ('duracionProyecto', models.FloatField()),
                ('idCodigo', models.CharField(max_length=200)),
                ('notas', models.CharField(max_length=1000)),
                ('fechaIniEstimada', models.DateField()),
                ('gav', models.FloatField()),
                ('estado', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=1000)),
                ('idValue', models.CharField(max_length=1000)),
                ('nombreCliente', models.CharField(max_length=1000)),
            ],
        ),
    ]
