# Generated by Django 4.0 on 2021-12-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0003_proyectitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectitem',
            name='idValue',
        ),
        migrations.AlterField(
            model_name='proyectitem',
            name='estado',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='proyectitem',
            name='idCodigo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='proyectitem',
            name='nombreCliente',
            field=models.CharField(max_length=200),
        ),
    ]
