# Generated by Django 4.0 on 2022-01-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0004_remove_proyectitem_idvalue_alter_proyectitem_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('idPersona', models.CharField(max_length=100)),
                ('proyectos', models.CharField(max_length=1000)),
                ('rutConsultor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('rut', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=1000)),
                ('direccion', models.CharField(max_length=1000)),
                ('profesion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectChiefItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('idPersona', models.CharField(max_length=100)),
                ('idProyecto', models.CharField(max_length=100)),
                ('rutConsultor', models.CharField(max_length=100)),
            ],
        ),
    ]
