# Generated by Django 4.0 on 2022-01-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0005_consultantitem_personaitem_proyectchiefitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonaItem',
            new_name='PersonItem',
        ),
    ]
