# Generated by Django 4.0 on 2022-01-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0006_rename_personaitem_personitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProyecto', models.CharField(max_length=100)),
                ('fechaPostulacion', models.DateField()),
                ('mesPostulacion', models.CharField(max_length=100)),
                ('mesAdjudicacion', models.CharField(max_length=100)),
                ('fechaVenta', models.DateField()),
                ('yearVenta', models.CharField(max_length=100)),
            ],
        ),
    ]
