# Generated by Django 4.0 on 2022-01-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0007_postulationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=500)),
                ('correoCliente', models.CharField(max_length=500)),
                ('idProyecto', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='postulationitem',
            name='idProyecto',
            field=models.CharField(max_length=1000),
        ),
    ]
